// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW6-DvbiGnPZIE86N4Fvg0_9K86JMrSyg',
    appId: '1:361542218933:web:ec7b08df76ca4fcd65bafc',
    messagingSenderId: '361542218933',
    projectId: 'my-freelanceapp-project',
    authDomain: 'my-freelanceapp-project.firebaseapp.com',
    storageBucket: 'my-freelanceapp-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsceHrYM952Q9pRufd-RlbOu-VwByy0Gk',
    appId: '1:361542218933:android:caf7123c896eece965bafc',
    messagingSenderId: '361542218933',
    projectId: 'my-freelanceapp-project',
    storageBucket: 'my-freelanceapp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIdeXcTs8CLkUKH5iP2vvCsCtfSyH9gXc',
    appId: '1:361542218933:ios:92918879506277d865bafc',
    messagingSenderId: '361542218933',
    projectId: 'my-freelanceapp-project',
    storageBucket: 'my-freelanceapp-project.appspot.com',
    iosClientId: '361542218933-bf23hhufh8cets7hokucqed086f47hrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelanceappLikeFiverr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIdeXcTs8CLkUKH5iP2vvCsCtfSyH9gXc',
    appId: '1:361542218933:ios:92918879506277d865bafc',
    messagingSenderId: '361542218933',
    projectId: 'my-freelanceapp-project',
    storageBucket: 'my-freelanceapp-project.appspot.com',
    iosClientId: '361542218933-bf23hhufh8cets7hokucqed086f47hrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelanceappLikeFiverr',
  );
}
